apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    app: result
spec:
  template:
    metadata:
      name: result
      labels:
        app: result
    spec:
      containers:
        - name: result
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80
              name: port
  selector:
    matchLabels:
      app: result
  replicas: 1
