apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: vote
spec:
  template:
    metadata:
      name: vote
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80
              name: port
  selector:
    matchLabels:
      app: vote
  replicas: 1
